server:
  port: 8766
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  application:
    name: service-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka