server:
  port: 8783
spring:
  application:
    name: service-hi
  jackson:
      serialization:
        INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth_server?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root

eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/
      #defaultZone 一定要按照标准写法，因为service-url的数据类型是Map 这算是个小坑需要注意

# JWT
jwt:
  header: Authorization
  expiration: 604800
  tokenHead: "Bearer "

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG